services:
  app:
    image: ghcr.io/forsideapps/sweetme-backend:latest
    container_name: sweetme-app
    environment:
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TNS_ADMIN=/wallet
    volumes:
      - ./backend/wallet:/wallet:ro
      - ./oci/config:/root/.oci/config:ro
      - ./oci/oci_api_key.pem:/root/.oci/oci_api_key.pem:ro
    mem_limit: 400m
    restart: unless-stopped
    networks:
      - sweetme

  nginx:
    image: ghcr.io/forsideapps/sweetme-nginx:latest
    container_name: sweetme-nginx
    ports:
      - "8880:80"
    mem_limit: 64m
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - sweetme


networks:
  sweetme:
    driver: bridge
